### ISSUE TITLE
Corner case for `#` appearing in strings

### ISSUE THREAD

**Issue by BurnerWah** [ikatyang/tree-sitter-toml#17]
Can be shown with this example: https://toml.io/en/v1.0.0-rc.3#comment

```toml
# This is a full-line comment
key = "value"  # This is a comment at the end of a line
another = "# This is not a comment"
```

Results in

```
comment [0, 0] - [0, 29]
pair [1, 0] - [1, 55]
  bare_key [1, 0] - [1, 3]
  string [1, 6] - [1, 13]
  comment [1, 15] - [1, 55]
ERROR [2, 0] - [3, 0]
  bare_key [2, 0] - [2, 7]
  comment [2, 11] - [2, 35]
```
