### ISSUE TITLE
Differentiate section title from regular keys?

### ISSUE THREAD

**Issue by adrian5** [ikatyang/tree-sitter-toml#26]
I'm writing this due to an aging [issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/2713) with nvim-treesitter.

Looking at the following example:

```toml
[database]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true
```

I'd like `database` or even `[database]` be style differently than e.g. `server` and `ports` (which GitHub happens to get right). I'm not sure nvim-treesitter just needs to employ better queries, or if the Tree-Sitter grammar could be improved. Apologies if it's the former, I just wanted to get some feedback on this.
